
package unicesumar;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import unicesumar.Responsavel;

public class TelaResponsavel extends JFrame {
    private JTextField txtNome, txtCpf, txtTelefone, txtEmail, txtEndereco, txtIdade;
    private JButton btnAvancar;
    
    public TelaResponsavel() {
        // Configuração dao tamanho da tela
        setTitle("Etapa 1 de 3 - Dados do Responsável");
        setSize(500, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new GridLayout(8, 2, 5, 5)); // 8 linhas, 2 colunas, espaçamentos entre eles

        // Inicialização e adição de componentes
        add(new JLabel("Etapa 1 de 3 - Dados do Responsável"));
        add(new JLabel()); //espaço vazio para alinhamento da grid
        
        add(new JLabel("Nome:"));
        txtNome = new JTextField();
        add(txtNome);

        add(new JLabel("CPF:"));
        txtCpf = new JTextField();
        add(txtCpf);

        add(new JLabel("Telefone:"));
        txtTelefone = new JTextField();
        add(txtTelefone);

        add(new JLabel("Email:"));
        txtEmail = new JTextField();
        add(txtEmail);

        add(new JLabel("Endereço:"));
        txtEndereco = new JTextField();
        add(txtEndereco);

        add(new JLabel("Idade:"));
        txtIdade = new JTextField();
        add(txtIdade);
        
        add(new JLabel());//espaço vazio para alinhamento da grid
        
        btnAvancar = new JButton("Avançar");
        btnAvancar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                avancarAction();
            }
        });
        add(btnAvancar);

        // Centraliza a tela
        setLocationRelativeTo(null);
    
    }
    //função para avanço entre as telas
    private void avancarAction() {
        try {
            Responsavel responsavel = new Responsavel();
            responsavel.setNome(txtNome.getText());
            responsavel.setCpf(txtCpf.getText());
            responsavel.setTelefone(txtTelefone.getText());
            responsavel.setEmail(txtEmail.getText());
            responsavel.setEndereco(txtEndereco.getText());
            responsavel.setIdade(Integer.parseInt(txtIdade.getText()));

            if (responsavel.getIdade() < 18) {
                JOptionPane.showMessageDialog(this, "O responsável deve ser maior de idade.");
                return;
            }

            // Criação da próxima tela, passando o objeto responsável
            TelaCrianca telaCrianca = new TelaCrianca(responsavel);
            telaCrianca.setVisible(true);
            this.dispose(); // Fecha a tela atual

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor, insira uma idade válida.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //inicialização da tela atual
                new TelaResponsavel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
